src/Tree/Node/NodeTrait.php

This saves an allocation (from setChildren resetting `$this->children` to an empty array) and a decent amount of time during construction (from not allocating and not calling various functions).

Don't setChildren if no children to set

---

src/Tree/Node/NodeTrait.php
tests/Tree/Node/NodeTest.php

getSize method return number of a nodes in a tree. Unit test method included in PR.

getSize of the tree and parts of it

---

src/Visitor/PostOrderVisitor.php
src/Visitor/PreOrderVisitor.php
tests/Visitor/PostOrderVisitorTest.php
tests/Visitor/PreOrderVisitorTest.php

This PR
Follows https://twitter.com/localheinz/status/633893849392377856.

Enhancement: Implement pre- and post-order walkers

---

tests/Node/NodeTest.php

Fix: Remove empty setUp()

---

.travis.yml
CHANGELOG.md

Fix: Drop support for HHVM

---

composer.json
composer.lock

The test suite makes use of \PHPUnit_Framework_TestCase, which is from earlier versions of PHPUnit (<6.0). This updates the test suite, and adds PHPUnit as an explicit dev dependency in composer.json.

Fix: Require phpunit/phpunit

---

src/Node/Node.php
src/Node/NodeTrait.php

This is a Variant to your Tree project, where the constructor is in the Node class rather than in the Trait.
This allows for other classes implementing the NodeInterface, to be able to use the NodeTrait but have a different constructor that suits that Node behavior/requirements (i.e. Have more attributes than just value, and constructor requires all of them).

Variant to Node, constructor is in the Node class instead of Trait

---

.github/dependabot.yml

Fix: Increase versions in composer.json

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 5.6

---

.github/workflows/integrate.yaml
Makefile
composer.json
composer.lock

Enhancement: Require and use ergebnis/composer-normalize

---

.github/CONTRIBUTING.md
.github/workflows/integrate.yaml
.gitignore
.php_cs
Makefile
composer.json
composer.lock
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
src/Node/Node.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php
src/Visitor/PostOrderVisitor.php
src/Visitor/PreOrderVisitor.php
src/Visitor/Visitor.php
src/Visitor/YieldVisitor.php
tests/Builder/NodeBuilderTest.php
tests/Node/NodeTest.php
tests/Visitor/PostOrderVisitorTest.php
tests/Visitor/PreOrderVisitorTest.php
tests/Visitor/YieldVisitorTest.php

Enhancement: Require and use ergebnis/php-cs-fixer-config

---

psalm-baseline.xml
src/Builder/NodeBuilderInterface.php
src/Node/Node.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php

From https://twitter.com/localheinz/status/1332251797226991616

Fix PHPStan problems and be explicit

---

CHANGELOG.md
psalm-baseline.xml
src/Node/NodeInterface.php
src/Node/NodeTrait.php

Fix: Add `getSize()` to `NodeInterface`

---

CHANGELOG.md
src/Node/NodeInterface.php
src/Node/NodeTrait.php

Fix: Add `root()` to `NodeInterface`

---

CHANGELOG.md
src/Node/NodeInterface.php

This pull request
Follows #113.

Fix: Use `static`

---

CHANGELOG.md
psalm-baseline.xml
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
src/Node/Node.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php

Fix: Add parameter type declarations

---

CHANGELOG.md
src/Node/NodeTrait.php
test/Unit/Node/NodeTest.php

Fix: Return empty `array` from `getNeighbors()` when node is root

---

CHANGELOG.md
src/Node/NodeTrait.php
test/Unit/Node/NodeTest.php

Fix: Return array with node from `getNeighborsAndSelf()` when node is root

---

.gitattributes
.github/CONTRIBUTING.md
.github/workflows/integrate.yaml
Makefile
composer.json
composer.lock
infection.json

Enhancement: Run mutation tests with `infection/infection`

---

CHANGELOG.md
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
test/Unit/Builder/NodeBuilderTest.php

Fix: Throw `LogicException` when attempting to get `Node` from empty `NodeBuilder`
