.travis.yml

This PR
:information_desk_person: See http://docs.travis-ci.com/user/workers/container-based-infrastructure/.

Enhancement: Direct builds to container-based infrastructure

---

src/Builder/NodeBuilder.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php

Fix: Docblocks

---

src/Builder/NodeBuilder.php

Fix: Remove unused import

---

README.md

Fix: Replace broken badges

---

tests/Builder/NodeBuilderTest.php
tests/Node/NodeTest.php
tests/Visitor/YieldVisitorTest.php

Fix: Assert sameness, not just equality

---

CHANGELOG.md
README.md

Enhancement: Extract changelog into separate file

---

CHANGELOG.md

Fix: Add missing reference

---

composer.json

Fix: Configure platform

---

.github/workflows/integrate.yaml

Enhancement: Validate composer.json and composer.lock

---

.github/dependabot.yml
.github/workflows/integrate.yaml

Enhancement: Add configuration for Dependabot

---

.github/workflows/integrate.yaml

Fix: Condition

---

.github/CONTRIBUTING.md
.github/workflows/release.yaml
README.md

Enhancement: Add workflow for creating release

---

.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 7.1

---

.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 7.2

---

.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 7.3

---

.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 7.4

---

.github/CONTRIBUTING.md
.github/workflows/integrate.yaml
Makefile
composer.json

Enhancement: Use ergebnis/composer-normalize to normalize composer.json

---

.github/dependabot.yml
.github/workflows/integrate.yaml

Enhancement: Automatically merge updates to GitHub Actions

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 5.4

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 5.5

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 7.0

---

.gitattributes

Fix: Sort out .gitattributes

---

.php_cs
LICENSE
composer.json
composer.lock
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
src/Node/Node.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php
src/Visitor/PostOrderVisitor.php
src/Visitor/PreOrderVisitor.php
src/Visitor/Visitor.php
src/Visitor/YieldVisitor.php
tests/Builder/NodeBuilderTest.php
tests/Node/NodeTest.php
tests/Visitor/PostOrderVisitorTest.php
tests/Visitor/PreOrderVisitorTest.php
tests/Visitor/YieldVisitorTest.php

Enhancement: Require and use ergebnis/license

---

.php_cs
LICENSE.md
README.md
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
src/Node/Node.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php
src/Visitor/PostOrderVisitor.php
src/Visitor/PreOrderVisitor.php
src/Visitor/Visitor.php
src/Visitor/YieldVisitor.php
tests/Builder/NodeBuilderTest.php
tests/Node/NodeTest.php
tests/Visitor/PostOrderVisitorTest.php
tests/Visitor/PreOrderVisitorTest.php
tests/Visitor/YieldVisitorTest.php

Enhancement: Use Markdown license

---

README.md

Enhancement: Reference CONTRIBUTING.md in README.md

---

README.md

Fix: Simplify installation instructions

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 7.1

---

.github/workflows/integrate.yaml
CHANGELOG.md

Enhancement: Add support for PHP 8.1

---

.gitattributes
.github/CONTRIBUTING.md
.github/workflows/integrate.yaml
Makefile
README.md
composer.json
composer.lock
psalm-baseline.xml
psalm.xml

Enhancement: Require and use `vimeo/psalm`

---

.github/workflows/integrate.yaml

Enhancement: Run tests on PHP 8.2

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 7.2

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 7.3

---

.github/workflows/integrate.yaml
CHANGELOG.md
composer.json
composer.lock

Fix: Drop support for PHP 7.4

---

CHANGELOG.md
psalm-baseline.xml
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php
src/Node/NodeInterface.php
src/Node/NodeTrait.php
src/Visitor/PostOrderVisitor.php
src/Visitor/PreOrderVisitor.php
src/Visitor/Visitor.php
src/Visitor/YieldVisitor.php

Fix: Add return type declarations

---

CHANGELOG.md
src/Node/NodeInterface.php

This pull request
Follows #113.

Fix: Add return type declaration

---

CHANGELOG.md
src/Node/NodeTrait.php

Fix: Add property type declarations

---

CHANGELOG.md
psalm-baseline.xml
src/Builder/NodeBuilder.php
src/Builder/NodeBuilderInterface.php

Enhancement: Use variadics

---

.github/workflows/integrate.yaml

Fix: Unset `platform` configuration as needed
